use_frameworks!

platform :ios, '8.0'

target 'XZQSMSSendButtonTool_Example' do
  pod 'XZQSMSSendButtonTool', :path => '../'

  target 'XZQSMSSendButtonTool_Tests' do
    inherit! :search_paths

    
  end
end
